package ru.messenger.chaosmessenger.message.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Per-device encrypted message envelope.
 *
 * <p>When a message is sent, one envelope is created for every active device of every
 * chat participant — including the sender's own devices so that sent messages remain
 * readable after a page reload.
 *
 * <p>Envelope structure follows the Signal X3DH protocol:
 * <ol>
 *   <li>Sender generates an ephemeral key pair {@link #ephemeralPublicKey}</li>
 *   <li>Performs X25519 key agreement with the recipient's key bundle</li>
 *   <li>Derives a symmetric key via HKDF</li>
 *   <li>Encrypts the message and stores {@link #ciphertext} + {@link #nonce}</li>
 * </ol>
 *
 * <p>The constraint {@code (message_id, target_device_id)} is unique —
 * only one envelope per device per message is allowed.
 */
@Entity
@Table(name = "message_envelopes",
        uniqueConstraints = @UniqueConstraint(columnNames = {"message_id", "target_device_id"}))
@Getter
@Setter
public class MessageEnvelope {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Reference to the parent {@link Message}. */
    @Column(name = "message_id", nullable = false)
    private Long messageId;

    /** Chat ID — denormalised to allow fast per-chat queries without a JOIN. */
    @Column(name = "chat_id", nullable = false)
    private Long chatId;

    /** Recipient user ID. */
    @Column(name = "target_user_id", nullable = false)
    private Long targetUserId;

    /** Surrogate PK of the recipient device from the {@code user_devices} table. */
    @Column(name = "target_device_db_id", nullable = false)
    private Long targetDeviceDbId;

    /**
     * String ID of the recipient device.
     * Used as the WebSocket topic address: {@code /topic/devices/{targetDeviceId}/chats/{chatId}}.
     */
    @Column(name = "target_device_id", nullable = false, length = 100)
    private String targetDeviceId;

    /** Sender user ID. */
    @Column(name = "sender_user_id", nullable = false)
    private Long senderUserId;

    /** String ID of the sender device. */
    @Column(name = "sender_device_id", nullable = false, length = 100)
    private String senderDeviceId;

    /**
     * Crypto operation type: {@code "PREKEY_WHISPER"} for the first message in a session (X3DH),
     * {@code "WHISPER"} for subsequent messages (Symmetric Ratchet).
     */
    @Column(name = "message_type", nullable = false, length = 40)
    private String messageType;

    /**
     * Base64-encoded sender identity public key (X25519).
     * Used by the recipient to verify the sender's identity during X3DH.
     */
    @Column(name = "sender_identity_public_key", nullable = false, columnDefinition = "text")
    private String senderIdentityPublicKey;

    /**
     * Base64-encoded ephemeral public key generated by the sender.
     * Present only for {@code messageType = "PREKEY_WHISPER"} (X3DH session initiation).
     * {@code null} for subsequent messages in an established session.
     */
    @Column(name = "ephemeral_public_key", columnDefinition = "text")
    private String ephemeralPublicKey;

    /** Base64-encoded encrypted message payload (AES-GCM). */
    @Column(nullable = false, columnDefinition = "text")
    private String ciphertext;

    /** Base64-encoded nonce (IV) required for decryption. Unique per envelope. */
    @Column(nullable = false, columnDefinition = "text")
    private String nonce;

    /**
     * Recipient's Signed PreKey ID used during X3DH.
     * Required by the recipient to reproduce the key agreement.
     * {@code null} for messages inside an already established session.
     */
    @Column(name = "signed_prekey_id")
    private Integer signedPreKeyId;

    /**
     * Recipient's One-Time PreKey ID used during X3DH.
     * {@code null} if no OTP was available or the session was already established.
     */
    @Column(name = "one_time_prekey_id")
    private Integer oneTimePreKeyId;

    /**
     * Sequential index of this message within the ratchet session (zero-based).
     * Used by the client to synchronise the receiving chain
     * when messages arrive out of order.
     */
    @Column(name = "message_index")
    private Integer messageIndex;

    /** Server-side creation timestamp of this envelope. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
