package ru.messenger.chaosmessenger.crypto.device;

import jakarta.persistence.*;
import lombok.*;
import ru.messenger.chaosmessenger.user.domain.User;

import java.time.LocalDateTime;

/**
 * A registered user device.
 *
 * <p>Each device holds its own cryptographic key set: an Identity Key,
 * a Signed PreKey, and a pool of One-Time PreKeys. This provides session
 * isolation — compromising one device does not expose conversations from
 * other devices belonging to the same user.
 *
 * <p>A device is active ({@link #active} = true) after registration.
 * When a device is replaced or the user logs out, the flag is cleared and the
 * server stops delivering envelopes to that device.
 *
 * <p>{@link #deviceId} is a client-generated string identifier (typically a UUID).
 * It is used as a WebSocket topic address and the value of the {@code X-Device-Id} header.
 */
@Entity
@Table(
        name = "user_devices",
        uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "device_id"})
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserDevice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this device.
     * Lazy-loaded to avoid fetching user data on every device lookup.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Client-generated string device identifier (UUID).
     * Sent with every request via the {@code X-Device-Id} header.
     * Unique within a single user's devices.
     */
    @Column(name = "device_id", nullable = false, length = 100)
    private String deviceId;

    /**
     * Registration ID in Signal Protocol terminology.
     * A random integer generated by the client at device registration time.
     * Used during X3DH session establishment.
     */
    @Column(name = "registration_id", nullable = false)
    private Integer registrationId;

    /**
     * Human-readable device name set by the user (e.g. "iPhone 15", "Work laptop").
     * Optional; used for display purposes only.
     */
    @Column(name = "device_name")
    private String deviceName;

    /**
     * Base64-encoded device Identity Key (X25519 raw public key).
     * Long-term — does not change for the lifetime of the device.
     * Used by other participants during X3DH ECDH key agreement.
     */
    @Column(name = "identity_public_key", nullable = false, columnDefinition = "TEXT")
    private String identityPublicKey;

    /**
     * Base64-encoded SPKI public key (ECDSA P-256).
     * Used by the server to verify the SignedPreKey signature during X3DH device registration.
     * Separate from identityPublicKey: the identity key is used for ECDH, this key for signing.
     */
    @Column(name = "signing_public_key", columnDefinition = "TEXT")
    private String signingPublicKey;

    /**
     * Active flag. When {@code false} the device is deactivated and
     * no new envelopes will be delivered to it.
     */
    @Column(name = "is_active", nullable = false)
    private boolean active;

    /**
     * Timestamp of the device's last activity.
     * Updated on every WebSocket connection.
     */
    @Column(name = "last_seen")
    private LocalDateTime lastSeen;

    /** Device registration timestamp. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
